---

- name: Unregister from Red Hat insights.
  become: true
  command: insights-client --unregister
  listen: "reregister of Red Hat Insights"

- name: Register on Red Hat insights.
  become: true
  command: insights-client --register
  listen: "reregister of Red Hat Insights"

- name: Upload data to Red Hat insights.
  become: true
  command: insights-client
  listen: "reregister of Red Hat Insights"

- name: Performs a test scan and upload the results to Red Hat insights.
  become: true
  command: insights-client --collector malware-detection
  listen: "testscan and upload to Red Hat Insights"
